### ISSUE TITLE
Kubeadm安装Kubernetes集群

### ISSUE THREAD

**Issue by kntvops** [kntvops/Spring-Boot-App#1]
# Kubeadm 安装 Kubernetes 集群

使用Kubeadm快速部署Kubernetes集群，操作系统为CentOS 7.6.1810 X86_64，用到的各相关程序版本如下

- Kubernetes: v1.28.6
- Docker: 24.0.8
- Cri-dockerd: v0.3.8
- Metrics-Server: v0.7.0
- Dashboard: v2.7.0

**系统环境说明**

|主机地址| 节点名称 | 角色|
| -- | -- | -- |
|192.168.122.111| k8s-master-01 | master,etcd|
|192.168.122.211| k8s-worker-01 | worker|
|192.168.122.212| k8s-worker-02 | worker|
|192.168.122.213| k8s-worker-03 | worker|

## 安装环境准备

- 主机名

```
hostnamectl  set-hostname k8s-master-01
hostnamectl  set-hostname k8s-worker-01
hostnamectl  set-hostname k8s-worker-02
hostnamectl  set-hostname k8s-worker-03
```

- 主机名解析

```
cat << EOF >> /etc/hosts

192.168.122.111 k8s-master-01 master
192.168.122.211 k8s-worker-01 worker-01
192.168.122.212 k8s-worker-02 worker-02
192.168.122.213 k8s-worker-03 worker-03
192.168.122.111 k8s-vip.linux.io  k8s-vip
EOF
```

> k8s-vip.linux.io 预留出来用于以后扩展为高可用集群

- 关闭防火墙

```
systemctl  stop firewalld && systemctl disable firewalld
```

- 关闭selinux

```
sed -i 's@SELINUX=enforcing@SELINUX=disabled@g' /etc/selinux/config
setenforce  0
```

- 关闭swap分区

```
sed -i 's/.*swap.*/#&/' /etc/fstab
swapoff -a
```

- 时间同步

```
/usr/sbin/ntpdate ntp.aliyun.com
echo "*/3 * * * * /usr/sbin/ntpdate ntp.aliyun.com &> /dev/null" > /var/spool/cron/root
```

- 打开路由转发以及网桥过滤

```
# 加载过滤模块
modprobe br_netfilter
cat << EOF >> /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF
sysctl -p
```

- 配置IPVS模块

```
yum -y install ipset ipvsadm
```
```
cat > /etc/sysconfig/modules/ipvs.modules <<EOF
#!/bin/bash
modprobe -- ip_vs
modprobe -- ip_vs_rr
modprobe -- ip_vs_wrr
modprobe -- ip_vs_sh
modprobe -- nf_conntrack
EOF
```
```
chmod 755 /etc/sysconfig/modules/ipvs.modules
bash /etc/sysconfig/modules/ipvs.modules
lsmod | grep -e ip_vs -e nf_conntrack
```

- 升级内核

```
# 载入公钥
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
# 安装ELRepo
rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
# 载入elrepo-kernel元数据
yum --disablerepo=\* --enablerepo=elrepo-kernel repolist
# 查看可用的rpm包
yum --disablerepo=\* --enablerepo=elrepo-kernel list kernel*
# 安装长期支持版本的kernel
yum --disablerepo=\* --enablerepo=elrepo-kernel install -y kernel-lt.x86_64
# 删除旧版本工具包
yum remove kernel-tools-libs.x86_64 kernel-tools.x86_64 -y
# 安装新版本工具包
yum --disablerepo=\* --enablerepo=elrepo-kernel install -y kernel-lt-tools.x86_64
```
```
#查看默认启动顺序
awk -F\' '$1=="menuentry " {print $2}' /etc/grub2.cfg  
CentOS Linux 7 Rescue c941d17f6618a89ea4e2106496d6242b (5.4.268-1.el7.elrepo.x86_64)
CentOS Linux (5.4.268-1.el7.elrepo.x86_64) 7 (Core)
CentOS Linux (3.10.0-957.el7.x86_64) 7 (Core)
CentOS Linux (0-rescue-c27451570be14505850ccc9fb1a2f85d) 7 (Core)
#默认启动的顺序是从0开始，新内核是从头插入（目前位置在0，而5.4.268的是在1），所以需要选择1。
grub2-set-default 1
#重启并检查
reboot
```

#### 安装DOCKER

- 安装软件包

```
# step 1: 安装必要的一些系统工具
sudo yum install -y yum-utils device-mapper-persistent-data lvm2
# Step 2: 添加软件源信息
sudo yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
# Step 3
sudo sed -i 's+download.docker.com+mirrors.aliyun.com/docker-ce+' /etc/yum.repos.d/docker-ce.repo
# Step 4: 更新并安装Docker-CE
sudo yum makecache fast
sudo yum -y install docker-ce-24.0.8
# Step 4: 开启Docker服务
sudo service docker start
```

> 查看版本： yum list docker-ce.x86_64 --showduplicates | sort -r

- 配置DOCKER

```
cat << EOF >> /etc/docker/daemon.json
{
    "exec-opts": ["native.cgroupdriver=systemd"],
    "registry-mirrors": ["https://o4uba187.mirror.aliyuncs.com"]
}
EOF
```

- 重启并设置开机启动

```
systemctl daemon-reload
systemctl  restart docker
systemctl  enable docker
```

#### 安装CRI-DOCKERD

- 安装软件包

```
wget https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.8/cri-dockerd-0.3.8-3.el7.x86_64.rpm
rpm -ivh cri-dockerd-0.3.8-3.el7.x86_64.rpm
```

- 配置CRI-DOCKERD

```
sed -i 's@ExecStart=/usr/bin/cri-dockerd@ExecStart=/usr/bin/cri-dockerd --pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9 @g' /usr/lib/systemd/system/cri-docker.service
```

- 重启并设置开机启动

```
systemctl daemon-reload
systemctl restart cri-docker && systemctl  enable  cri-docker
```

#### 安装软件

- 配置软件源

```
cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://mirrors.aliyun.com/kubernetes-new/core/stable/v1.28/rpm/
enabled=1
gpgcheck=1
gpgkey=https://mirrors.aliyun.com/kubernetes-new/core/stable/v1.28/rpm/repodata/repomd.xml.key
EOF

```

- 安装软件包

```
#  yum list kubeadm  --showduplicates | sort -r
yum install -y kubelet-1.28.6 kubeadm-1.28.6 kubectl-1.28.6
```

> 由于官网未开放同步方式, 可能会有索引gpg检查失败的情况, 这时请用 yum install -y --nogpgcheck kubelet kubeadm kubectl 安装

#### 设置KUBELET

```
sed -i 's@KUBELET_EXTRA_ARGS=@KUBELET_EXTRA_ARGS="--cgroup-driver=systemd"@' /etc/sysconfig/kubelet
systemctl enable kubelet
```

#### 集群初始化

- 生成kubeadm config 文件

```
kubeadm config print init-defaults --component-configs KubeProxyConfiguration,KubeletConfiguration > kubeadm-init.yaml
```
> 列出所需镜像: kubeadm config images list --kubernetes-version=v1.28.6

```
cat kubeadm-init.yaml
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 0.0.0.0 #
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock #
  imagePullPolicy: IfNotPresent
#  pod-infra-container-image: registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9
  name: k8s-master-01
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: "k8s-vip.linux.io:6443" #
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers #
kind: ClusterConfiguration
kubernetesVersion: 1.28.6
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.244.0.0/16
scheduler: {}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
bindAddressHardFail: false
clientConnection:
  acceptContentTypes: ""
  burst: 0
  contentType: ""
  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
  qps: 0
clusterCIDR: ""
configSyncPeriod: 0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
detectLocal:
  bridgeInterface: ""
  interfaceNamePrefix: ""
detectLocalMode: ""
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
  localhostNodePorts: null
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 0s
  syncPeriod: 0s
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 0s
  tcpFinTimeout: 0s
  tcpTimeout: 0s
  udpTimeout: 0s
kind: KubeProxyConfiguration
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: 0
metricsBindAddress: ""
mode: "ipvs"
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
showHiddenMetricsForVersion: ""
winkernel:
  enableDSR: false
  forwardHealthCheckVip: false
  networkName: ""
  rootHnsEndpointName: ""
  sourceVip: ""
---
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupDriver: systemd
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
containerRuntimeEndpoint: ""
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: 0
memorySwap: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
rotateCertificates: true
runtimeRequestTimeout: 0s
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
```

- 初始化主节点-Init

```
kubeadm  init --config kubeadm-init.yaml  
[init] Using Kubernetes version: v1.28.6
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [k8s-master-01 k8s-vip.linux.io kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.122.111]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [k8s-master-01 localhost] and IPs [192.168.122.111 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [k8s-master-01 localhost] and IPs [192.168.122.111 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[apiclient] All control plane components are healthy after 8.515036 seconds
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config" in namespace kube-system with the configuration for the kubelets in the cluster
[upload-certs] Skipping phase. Please see --upload-certs
[mark-control-plane] Marking the node k8s-master-01 as control-plane by adding the labels: [node-role.kubernetes.io/control-plane node.kubernetes.io/exclude-from-external-load-balancers]
[mark-control-plane] Marking the node k8s-master-01 as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule]
[bootstrap-token] Using token: abcdef.0123456789abcdef
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to get nodes
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[kubelet-finalize] Updating "/etc/kubernetes/kubelet.conf" to point to a rotatable kubelet client certificate and key
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

Alternatively, if you are the root user, you can run:

  export KUBECONFIG=/etc/kubernetes/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

You can now join any number of control-plane nodes by copying certificate authorities
and service account keys on each node and then running the following as root:

  kubeadm join k8s-vip.linux.io:6443 --token abcdef.0123456789abcdef \
        --discovery-token-ca-cert-hash sha256:7bce2222ecd37afbb92614b99746d7071dc4cadd79d28af16389c340f91c346a \
        --control-plane

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join k8s-vip.linux.io:6443 --token abcdef.0123456789abcdef \
        --discovery-token-ca-cert-hash sha256:7bce2222ecd37afbb92614b99746d7071dc4cadd79d28af16389c340f91c346a
```

- 配置KUBECONFIG

```
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

- 加入Worker节点-Join

```
kubeadm join k8s-vip.linux.io:6443 --token abcdef.0123456789abcdef \
        --discovery-token-ca-cert-hash sha256:7bce2222ecd37afbb92614b99746d7071dc4cadd79d28af16389c340f91c346a \
        --cri-socket   unix:///var/run/cri-dockerd.sock
```

> 如果报错register.k8s.io/pause镜像拉不下来，重启 kubelet 和 cri-docker可解决

- 部署网络Calico网络

```
curl https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml -O
# 取消注释：CALICO_IPV4POOL_CIDR，并修改网段为 10.244.0.0/16

kubectl apply -f calico.yaml
```

## 验证集群

- 查看POD状态

```
kubectl  get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-5fc7d6cf67-f7nhf   1/1     Running   0          10m
kube-system   calico-node-4hwxz                          1/1     Running   0          10m
kube-system   calico-node-bmt95                          1/1     Running   0          10m
kube-system   calico-node-gwdx5                          1/1     Running   0          10m
kube-system   calico-node-r6gp6                          1/1     Running   0          10m
kube-system   coredns-6554b8b87f-mkp5p                   1/1     Running   0          70m
kube-system   coredns-6554b8b87f-whsgt                   1/1     Running   0          70m
kube-system   etcd-k8s-master-01                         1/1     Running   0          70m
kube-system   kube-apiserver-k8s-master-01               1/1     Running   0          70m
kube-system   kube-controller-manager-k8s-master-01      1/1     Running   0          70m
kube-system   kube-proxy-gf2mq                           1/1     Running   0          70m
kube-system   kube-proxy-pjhnb                           1/1     Running   0          69m
kube-system   kube-proxy-qqr96                           1/1     Running   0          69m
kube-system   kube-proxy-z9tpd                           1/1     Running   0          69m
kube-system   kube-scheduler-k8s-master-01               1/1     Running   0          70m
```

- 测试部署

```
kubectl  create deployment myapp --image=ikubernetes/myapp:v1 --replicas=5
kubectl  get pod -o wide
NAME                     READY   STATUS    RESTARTS   AGE     IP              NODE            NOMINATED NODE   READINESS GATES
myapp-5d9c4b4647-d6pt4   1/1     Running   0          5m38s   10.244.36.194   k8s-worker-01   <none>           <none>
myapp-5d9c4b4647-mg29j   1/1     Running   0          5m38s   10.244.118.66   k8s-worker-02   <none>           <none>
myapp-5d9c4b4647-msq2s   1/1     Running   0          5m38s   10.244.7.131    k8s-worker-03   <none>           <none>
myapp-5d9c4b4647-snnpk   1/1     Running   0          5m38s   10.244.118.65   k8s-worker-02   <none>           <none>
myapp-5d9c4b4647-w5g69   1/1     Running   0          5m38s   10.244.36.193   k8s-worker-01   <none>           <none>
```
```
kubectl expose deployment myapp --port=80 --target-port=80 --type="NodePort"                
kubectl  get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        80m
myapp        NodePort    10.102.87.202   <none>        80:31749/TCP   4s

1 | <a href="hostname.html">Pod Name</a>
[root@k8s-master-01 ~]# for i in `seq 5`;do curl 10.102.87.202/hostname.html;done
myapp-5d9c4b4647-mg29j
myapp-5d9c4b4647-snnpk
myapp-5d9c4b4647-msq2s
myapp-5d9c4b4647-d6pt4
myapp-5d9c4b4647-w5g69
```
```
kubectl get svc -n kube-system
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   82m

yum install -y bind-utils 
dig -t A myapp.default.svc.cluster.local @10.96.0.10 

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.15 <<>> -t A myapp.default.svc.cluster.local @10.96.0.10
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31402
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;myapp.default.svc.cluster.local. IN    A

;; ANSWER SECTION:
myapp.default.svc.cluster.local. 30 IN  A       10.102.87.202

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Fri Feb 02 13:42:21 CST 2024
;; MSG SIZE  rcvd: 107
```

#### metrics-server

- 下载部署文件

```
wget  https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.0/components.yaml
```

- 修改部署文件
```
 vim components.yaml
 spec:
  containers:
  - args:
    - --cert-dir=/tmp
    - --secure-port=10250
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
    - --kubelet-insecure-tls # 添加此行
    image: k8s.dockerproxy.com//metrics-server/metrics-server:v0.7.0 # 修改镜像地址
        imagePullPolicy: IfNotPresent
```

- 执行部署

```
kubectl  apply -f components.yaml
```

- 验证

```
[root@k8s-master-01 ~]# kubectl  top nodes
NAME            CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
k8s-master-01   170m         8%     1834Mi          23%       
k8s-worker-01   74m          3%     1467Mi          18%       
k8s-worker-02   78m          3%     886Mi           11%       
k8s-worker-03   76m          3%     998Mi           12%       
[root@k8s-master-01 ~]# kubectl  top pods
NAME                     CPU(cores)   MEMORY(bytes)   
myapp-5d9c4b4647-d6pt4   0m           2Mi             
myapp-5d9c4b4647-mg29j   0m           1Mi             
myapp-5d9c4b4647-msq2s   0m           2Mi             
myapp-5d9c4b4647-snnpk   0m           2Mi             
myapp-5d9c4b4647-w5g69   0m           2Mi  
```

#### Dashboard

Kuboard是一个多集群管理工具

- 部署

```
kubectl  apply -f  https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
```

- 使用NodePort方式访问

```
kubectl  patch svc kubernetes-dashboard   -n kubernetes-dashboard -p '{"spec":{"type":"NodePort"}}'
service/kubernetes-dashboard patched
kubectl  get svc -n kubernetes-dashboard
NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
dashboard-metrics-scraper   ClusterIP   10.108.131.111   <none>        8000/TCP        3m42s
kubernetes-dashboard        NodePort    10.96.201.231    <none>        443:30795/TCP   3m42s
```

- 创建用户

```
cat admin-user.yaml 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard

kubectl apply -f admin-user.yaml 
```

- 获取令牌登录UI

```
kubectl -n kubernetes-dashboard create token admin-user
```
